#############################
# Xups for Hexo主题配置文件
# Jelon
# http://jelon.top
#############################

#----------------------------
# 头部导航
#----------------------------
menu:
  home:
    name: 首页
    link: /
    icon: icon-home
  lab:
    name: Github
    link: https://github.com/lijinhuai
    icon: icon-lab
  about:
    name: 关于
    link: /about/
    icon: icon-about
  comment:
    name: 留言
    link: /comment/
    icon: icon-comment

#----------------------------
# 副导航
#----------------------------
subnav:
  github: "#"
  weibo: "#"
  rss: "#"
  zhihu: "#"

#----------------------------
# RSS
#----------------------------
rss: /atom.xml

#----------------------------
# Favicon
#----------------------------
favicon: /favicon.ico

#----------------------------
# 头像url
#----------------------------
avatar: /img/jelon.jpg

#----------------------------
# 是否开启分享
#----------------------------
share: true

#----------------------------
# 侧栏是否显示微博秀
#----------------------------
weibo_show:
  enable: true
  code: <iframe width="100%" height="550" class="share_self"  frameborder="0" scrolling="no" src="http://widget.weibo.com/weiboshow/index.php?language=&width=0&height=550&fansRow=2&ptype=1&speed=0&skin=1&isTitle=1&noborder=1&isWeibo=1&isFans=1&uid=1689547105&verifier=d79d6a44&dpc=1"></iframe>

#----------------------------
# 是否使用网易云跟帖
#----------------------------
gentie:
  enable: false
  productKey: c06bb9930e6f4b38a9997cb9bd17aba5

#----------------------------
# 是否开启云标签
#----------------------------
tagcloud: true

#----------------------------
# 友情链接
#----------------------------
friends:
  enable: true
  list:
    1:
      name: 百度
      title: 百度
      link: https://www.baidu.com
    2:
      name: 阿里云
      title: 阿里云
      link: https://www.aliyun.com/

#----------------------------
# 头部链接
#----------------------------
head_links:
  enable: true
  list:
    sup:
      0:
        name: Github
        link: https://github.com/lijinhuai
      last:
        name: 百度统计
        link: http://tongji.baidu.com/web/welcome/login
    sub:
      sinaweibo:
        name: 新浪微博
        link: http://weibo.com/lijinhuai
#----------------------------
# SEO
#----------------------------
SEO:
  keywords: 你猜, 就不告诉你
  description: 个人博客

#----------------------------
# 百度分析
#----------------------------
baidu_analytics: true

#----------------------------
# 高亮样式
#----------------------------
highlight_theme: normal
#----------------------------
# CDN
#----------------------------
CDN: //7xs305.com1.z0.glb.clouddn.com/
